# Generated by Django 3.2.8 on 2022-04-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semestre', '0001_initial'),
        ('niveau', '0003_auto_20220407_1543'),
        ('ue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uemodel',
            name='code_p_n',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niveau.parcoursniveaumodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uemodel',
            name='code_semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='semestre.semestremodel'),
            preserve_default=False,
        ),
    ]
