# Generated by Django 3.2.8 on 2022-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiantmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='etudiantmodel',
            name='matricule',
            field=models.CharField(max_length=112),
        ),
    ]
