# Generated by Django 3.2.8 on 2022-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_alter_etudiantmodel_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantmodel',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
    ]
