# Generated by Django 3.2.8 on 2022-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_alter_etudiantmodel_sexe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiantmodel',
            options={'ordering': ['matricule']},
        ),
        migrations.AddField(
            model_name='etudiantmodel',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
