# Generated by Django 3.2.8 on 2022-03-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_auto_20220326_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiantmodel',
            name='slug',
        ),
    ]
