# Generated by Django 3.2.8 on 2022-03-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_remove_etudiantmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiantmodel',
            options={'ordering': ['nom']},
        ),
    ]
