# Generated by Django 3.2.8 on 2022-04-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niveau', '0003_auto_20220407_1543'),
        ('etudiant', '0008_alter_etudiantmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantmodel',
            name='code_p_n',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niveau.parcoursniveaumodel'),
            preserve_default=False,
        ),
    ]
