# Generated by Django 3.2.8 on 2022-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveau', '0003_auto_20220407_1543'),
        ('etudiant', '0009_etudiantmodel_code_p_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeEtudiantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_p_n', models.ManyToManyField(to='niveau.ParcoursNiveauModel')),
                ('etudiant', models.ManyToManyField(to='etudiant.EtudiantModel')),
            ],
        ),
    ]
