# Generated by Django 3.2.8 on 2022-04-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0010_listeetudiantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantmodel',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiantmodel',
            name='nationnalite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etudiantmodel',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.DeleteModel(
            name='ListeEtudiantModel',
        ),
    ]
