# Generated by Django 3.2.8 on 2022-04-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0001_initial'),
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcoursNiveauModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=144, null=True)),
                ('code_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveau.niveaumodel')),
                ('code_parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours.parcoursmodel')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
