# Generated by Django 3.2.8 on 2022-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveau', '0002_parcoursniveaumodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcoursniveaumodel',
            options={},
        ),
        migrations.AlterField(
            model_name='parcoursniveaumodel',
            name='description',
            field=models.CharField(default=1, max_length=144),
            preserve_default=False,
        ),
    ]
